# permissions for end users to view cordanodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cordanode-viewer-role
rules:
- apiGroups:
  - corda.orangesys.io
  resources:
  - cordanodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - corda.orangesys.io
  resources:
  - cordanodes/status
  verbs:
  - get
